version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker-compose -f docker-compose-standalone.yml  up -d
      - run:
          name: Waiting for Hbase to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 2888 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Hbase && exit 1
